version: '3'
services:
  react-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
  
  fastapi-backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    entrypoint: ["wait-for", "postgres:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jcl
    ports:
      - "5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    command: ["postgres"]